name: Go Build and Test
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Setup Go 1.12
      uses: actions/setup-go@v1
      with:
        go-version: 1.12
      id: go
    - name: Check out code
      uses: actions/checkout@v1
    - name: Build
      run: go build -v ./...
    - name: Test
      run: go test ./...
